version: 2
jobs:
  test:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gforth python
      - run:
          name: Run Tests
          command: python test/run-tests.py -v
