version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends gforth
      - run:
          name: Run Tests
          command: python test/run-tests.py -v
